import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import  java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ruvinya
 */
public class AddStudents extends javax.swing.JFrame {
    
    Connection  con  =  null;
    PreparedStatement  pst  =  null;
    
    
    public  void  clear(){
        jTextFieldStudentID.setText(" ");
        jTextFieldName.setText(" ");
        jComboBoxDepartment.getSelectedItem();
        jComboBoxBatch.getSelectedItem();
        jComboBoxCourse.getSelectedItem();
        jTextFieldEmailAddress.setText(" ");
       jTextFieldPhoneNumber.setText(" ");
        
    }

    /**
     * Creates new form AddStudents
     */
    public AddStudents() {
        con=database.connect();
        
        initComponents();
        setSize(1079,730);
        setLocation(570,170);
        setResizable(false);
        showDate();
        showTime();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
    }
    
        void showDate() {

        java.util.Date d = new java.util.Date();
        SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
        jLabelDate.setText(s.format(d));

    }

    void showTime() {

        new Timer(0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {

                java.util.Date d = new java.util.Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                jLabelTime.setText(s.format(d));
            }

        }).start();

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelStudentID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();
        jLabelBatch = new javax.swing.JLabel();
        jLabelEmailAddress = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jTextFieldStudentID = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        jComboBoxBatch = new javax.swing.JComboBox<>();
        jTextFieldEmailAddress = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jLabelDepartment = new javax.swing.JLabel();
        jComboBoxDepartment = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1079, 730));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1079, 730));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(140, 131, 129));
        jPanel1.setMinimumSize(new java.awt.Dimension(1079, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/unnamed (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 115));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 47, 76));
        jLabel2.setText("ADD  STUDENTS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabelStudentID.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabelStudentID.setForeground(new java.awt.Color(49, 47, 76));
        jLabelStudentID.setText("Student  ID");
        jPanel1.add(jLabelStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 184, -1, -1));

        jLabelName.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(49, 47, 76));
        jLabelName.setText("Name");
        jPanel1.add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 239, -1, 34));

        jLabelCourse.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabelCourse.setForeground(new java.awt.Color(49, 47, 76));
        jLabelCourse.setText("Course");
        jPanel1.add(jLabelCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 403, 99, -1));

        jLabelBatch.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabelBatch.setForeground(new java.awt.Color(49, 47, 76));
        jLabelBatch.setText("Batch");
        jPanel1.add(jLabelBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 348, -1, -1));

        jLabelEmailAddress.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabelEmailAddress.setForeground(new java.awt.Color(49, 47, 76));
        jLabelEmailAddress.setText("Email  Address");
        jPanel1.add(jLabelEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 458, -1, -1));

        jLabelPhoneNumber.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabelPhoneNumber.setForeground(new java.awt.Color(49, 47, 76));
        jLabelPhoneNumber.setText("Phone  Number");
        jPanel1.add(jLabelPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 513, -1, -1));

        jTextFieldStudentID.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldStudentID.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextFieldStudentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 189, 288, -1));

        jTextFieldName.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 244, 288, -1));

        jComboBoxCourse.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jComboBoxCourse.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software  Enginering", "Computer  Networks", "Computer  Security", "Business  Management", " " }));
        jPanel1.add(jComboBoxCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 408, 288, -1));

        jComboBoxBatch.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jComboBoxBatch.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxBatch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18.1", "18.2", "19.1", "19.2", "20.1", " " }));
        jPanel1.add(jComboBoxBatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 353, 288, -1));

        jTextFieldEmailAddress.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldEmailAddress.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailAddressActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 463, 288, -1));

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextFieldPhoneNumber.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jTextFieldPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 518, 288, -1));

        jLabelDepartment.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jLabelDepartment.setForeground(new java.awt.Color(49, 47, 76));
        jLabelDepartment.setText("Department");
        jPanel1.add(jLabelDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 293, -1, -1));

        jComboBoxDepartment.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jComboBoxDepartment.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxDepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SOC", "SOB", "SOE" }));
        jPanel1.add(jComboBoxDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 298, 288, -1));

        jButtonAdd.setBackground(new java.awt.Color(49, 47, 76));
        jButtonAdd.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-create-40 (2).png"))); // NOI18N
        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 590, 140, -1));

        jButtonClear.setBackground(new java.awt.Color(209, 117, 89));
        jButtonClear.setFont(new java.awt.Font("Dubai", 0, 20)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-erase-40.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 140, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/students.png"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Students"));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(724, 188, 320, 350));

        jLabelDate.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabelDate.setForeground(new java.awt.Color(0, 204, 102));
        jLabelDate.setText("Date");
        jPanel1.add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, -1, -1));

        jLabelTime.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabelTime.setForeground(new java.awt.Color(0, 204, 102));
        jLabelTime.setText("Time");
        jPanel1.add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 670, -1, -1));

        jLabelClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close-window-40.png"))); // NOI18N
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1024, 15, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1090, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JFrame frame;
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String studentID  =   jTextFieldStudentID.getText();
        String  name  =   jTextFieldName.getText();
        String  department  =  (String) jComboBoxDepartment.getSelectedItem();
        String  batch  =  (String) jComboBoxBatch.getSelectedItem();
        String  course  =  (String) jComboBoxCourse.getSelectedItem();
        String emailAddress  =   jTextFieldEmailAddress.getText();
        String  phoneNumber  =   jTextFieldPhoneNumber.getText();
        
        try{
            String query = " INSERT INTO student ( studentID , name , department , batch ,course , emailAddress , phoneNumber ) VALUES ('"+studentID+"','"+name+"','"+department+"','"+batch+"','"+course+"','"+emailAddress+"','"+phoneNumber+"')";
           
            pst  =   con.prepareStatement(query);
           pst.execute();
           
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
          JOptionPane.showMessageDialog(null, "Successfully  Updated");
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
      clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
   new Home().setVisible(true);this.dispose();
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jTextFieldEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailAddressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JComboBox<String> jComboBoxBatch;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<String> jComboBoxDepartment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelBatch;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDepartment;
    private javax.swing.JLabel jLabelEmailAddress;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelStudentID;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEmailAddress;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldStudentID;
    // End of variables declaration//GEN-END:variables
}
