/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Ruvinya
 */
public class lordings extends javax.swing.JFrame {
 public static void mains(){
 
    
        try{
             lordings ob = new  lordings();
         
        ob.setVisible(true);
        
        
             int c= 0;
         for(c =0; c<101; c++){
              
             Thread.sleep(100);
         ob.kl.setText(Integer.toString(c)+"%");
         
         ob.ps.setValue(c);
          
         if(c==100){
         ob.setVisible(false);
        Login aa = new Login();
      
         aa.setVisible(true);
         }
        
             
                  
         
             
             
       
     }
        
        }catch(Exception e){}
 }
    /**
     * Creates new form lordings
     */
    public lordings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ps = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ps.setBackground(new java.awt.Color(255, 255, 255));
        ps.setForeground(new java.awt.Color(0, 233, 20));
        ps.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ps.setBorderPainted(false);
        ps.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ps.setDoubleBuffered(true);
        getContentPane().add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, 10));

        jLabel2.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-books-emoji-48.png"))); // NOI18N
        jLabel2.setText("WELCOME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 330, 110));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/22.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 210));

        kl.setFont(new java.awt.Font("ZX81", 0, 3)); // NOI18N
        kl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(kl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 160, 30));

        setSize(new java.awt.Dimension(398, 211));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lordings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lordings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lordings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lordings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new lordings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kl;
    private javax.swing.JProgressBar ps;
    // End of variables declaration//GEN-END:variables
}
